### ISSUE TITLE
Upgrades at hatchery can be researched simultaneously.

### ISSUE THREAD

**Issue by jtsauls** [BurnySc2/sc2-planner#13]
Overlord speed and burrow are able to be researched simultaneously, as well as when a queen is being produced. 

They do not seem to respect the availability of an open hatchery. 

Great tool.

**Comment by BurnySc2** [comment]
Adding an example that should work sequentially after fix:

https://burnysc2.github.io/sc2-planner/?&race=zerg&bo=002eJyLrlbKTFGyMjQw0VEqqSxIVbJSKs8vyk4tUqrVIShlYQGXKS4pKk0uKS1KRUha4pEkzz4juERicklmfh6SHgO8lpnBZUvzMksQEkY4JMwQNpUWpBclpiAMMzPBlIoFABwBZgQ=
