### ISSUE TITLE
Cannot create supply structures (depot, pylon, overlord)

### ISSUE THREAD

**Issue by AveSharia** [BurnySc2/sc2-planner#17]
Just gave this a whirl but I get stuck at the ground floor: clicking the depot, pylon or overlord buttons does nothing!

If I try to drag the button onto the timeline, I am met with a circle-line icon (can't place). No error message is presented.

E

**Comment by BurnySc2** [comment]
To build structures, you are supposed to click at the bottom in the structures list. This should work:

![depot](https://i.imgur.com/zScnyog.png)
