### ISSUE TITLE
combat shields (ShieldWall) time off

### ISSUE THREAD

**Issue by jtsauls** [BurnySc2/sc2-planner#18]
True research time is [79s](https://liquipedia.net/starcraft2/Combat_Shield) but comes up on the planner as almost 2minutes.

**Comment by BurnySc2** [comment]
Can you give me an example build order (with link) where this is incorrect?
It looks correct to me:
[Build order](https://burnysc2.github.io/sc2-planner/?&race=terran&bo=002eJyLrlbKTFGyMrTUUSqpLEhVslIqLikqTS4pLUpVqtWBSBoZ4pM0wCcJl0tMLsnMz4NLGJvj0WVoBpcsLUgvSkwBSsUCABBGNqM=)
![combatshield](https://imgur.com/KxiNxeo.png)

**Comment by jtsauls** [comment]
Apologies for the hasty issue. Upon further investigation the issue is that combat shields can begin before stim is finished. But it still requires 79seconds after stim is finish to be completed, leading to a longer than normal research time. Same effect for concussive shells. 

See this [BO](https://burnysc2.github.io/sc2-planner/?&race=terran&settings=tLuDriterisSritZnrisEritm2JsIGJKuFtN&bo=002eJyLrlbKTFGyMjHVUSqpLEhVslIqzy/KTi1SqtUhJGNoCZcpLikqTS4pLUolQpuRIR5tRgb4JOFyicklmfl5cAljczy6DBEuKS1IL0pMQZIywy1ljikVCwBZ91/l). 

This also lead to strange behavior where you can change the order of the upgrades in the bar at the top in a way that should not be allowed.

**Comment by jtsauls** [comment]
[TechLab upgrades on Factory](https://burnysc2.github.io/sc2-planner/?&race=terran&settings=tLuDriterisSritZnrisEritm2JsIGJKuFtN&bo=002eJyLrlbKTFGyMjHVUSqpLEhVslIqzy/KTi1SqtUhJGNoCZcpLikqTS4pLUolQpuRIR5tRgb4JOFyicklmfl5CAlzPLqM8TnTCJ+koYkJXLa0IL0oMSUVm+cxpPBpMzLClIsFAFfne94=) and [TechLab on Starport](https://burnysc2.github.io/sc2-planner/?&race=terran&settings=tLuDriterisSritZnrisEritm2JsIGJKuFtN&bo=002eJyLrlbKTFGyMjHVUSqpLEhVslIqzy/KTi1SqtUhJGNoCZcpLikqTS4pLUolQpuRIR5tRgb4JOFyicklmfl5CAlzfLos8DkTr2MQFpYWpBclpiCkDI3NcMoh+QEuFQsA15By/g==) have this bug as well. But not the other upgrades on the Engineering bay, Armory, or Fusion core.

**Comment by BurnySc2** [comment]
I've found another bug where unit construction would block the addon from researching:
![Screenshot_2021-01-22_08-57-16](https://user-images.githubusercontent.com/21288725/105463251-0e4e7180-5c90-11eb-8c54-300201cdd93c.png)

But this is now also resolved:
![Screenshot_2021-01-22_08-57-41](https://user-images.githubusercontent.com/21288725/105463266-13abbc00-5c90-11eb-9f28-6a22aad827b1.png)

Internally it was queueing the upgrade without checking if the addon was still busy.

Thanks for the find!
