### ISSUE TITLE
Upgrades may be researched multiple times

### ISSUE THREAD

**Issue by BurnySc2** [BurnySc2/sc2-planner#22]
Once researched, an upgrade should not be researchable again.

Example [bo](https://burnysc2.github.io/sc2-planner/?&race=terran&settings=tLuDriterisSritZnrisEritm2JsIGJKuFtN&bo=002eJyLrlbKTFGyMjHVUSqpLEhVslIqzy/KTi1SqtUhJGNoCZcpLikqTS4pLUolQpuRIR5tRgb4JOFyicklmfl5CAlzPLqM8TnTCJ+koYkJXLa0IL0oMSUVm+cxpPBpMzLClIsFAFfne94=)
Bo given by https://github.com/BurnySc2/sc2-planner/issues/18#issuecomment-764218650

**Comment by paskausks** [comment]
I could try and do this one!

**Comment by BurnySc2** [comment]
Fixed in https://github.com/BurnySc2/sc2-planner/pull/36
However it could also require an error message if possible.
