### ISSUE TITLE
Mine from gas should always wait for available refineries

### ISSUE THREAD

**Issue by Kered13** [BurnySc2/sc2-planner#3]
Example:

https://burnysc2.github.io/sc2-planner/?&race=terran&bo=uDritmrisSJEritSf2HtL2NtZU2HsKI2PtkuBtgV2KritjkilTkli2MuFsExdkxcJtR2ZtZfexZbtNuF

The first 3xMine from gas command will wait for the first refinery to finish, however the second 3xMine from gas command does not wait for the second refinery. Since there is no reason to ever have more than 3 workers on one gas, mine from gas commands should wait for sufficient free refineries before running.

**Comment by BurnySc2** [comment]
Fixed in https://github.com/BurnySc2/sc2-planner/commit/835c264f4d949a7b3e75b6ae59210140ef46f491
