### ISSUE TITLE
Backward compatability.

### ISSUE THREAD

**Issue by elmonodecodigo** [BurnySc2/sc2-planner#34]
https://burnysc2.github.io/sc2-planner/?&race=terran&settings=tLuDriterisSritiYrisEritm2JsLuFtN&optimizeSettings=tLuDriterisSritdnsJrisEritm2KsIuFtN&bo=002eJyLrlbKTFGyMjHVUSqpLEhVslIqzy/KTi1SqtUhJGNoCZcpLikqTS4pLUolQpuRAXnaDMnTBpdITC7JzM8jQgseHxsb4XGEsQUeSUN8kkbm+HTiC2ZzanoPf8wgPFCal1lCWBy3A0g0yciEujFvTF66NTbG4Ty80Y43xZAUSbEA55kpyw==

The new version displays blanks when clicking links created with the old (pre Sept 27) links.

**Comment by BurnySc2** [comment]
Also doesn't work with new links atm :/
I'll investigate

**Comment by BurnySc2** [comment]
Thank @pikiou for the optimize functionality :)

**Comment by BurnySc2** [comment]
Should be fixed now. Let me know if I introduced more bugs.

**Comment by elmonodecodigo** [comment]
You are amazing!  Works brilliantly!  Thank you!
