### ISSUE TITLE
Feature Request: Show available resources at a given point in the timeline.

### ISSUE THREAD

**Issue by Kered13** [BurnySc2/sc2-planner#4]
Hypothetical UX: User clicks on a time in the timeline. The resources in the top right (or perhaps in a separate window) update to show the available resources at that time. It would be even better if this could also show what units and structures exist and what are in progress at this time.

This would help users find where new production can be inserted.

**Comment by BurnySc2** [comment]
There are selection bars which can be clicked at to relocate them (at the top in the build order), or use globally site-wide left- or right-arrow keys (you can use shift or ctrl modifier to jump further) to move them.
On the right next to the selected bar, new build order items will be inserted.
