### ISSUE TITLE
how to update to 5.0.11 patch ?

### ISSUE THREAD

**Issue by n7ck** [BurnySc2/sc2-planner#46]
Like Sentry Build time is now 23 seconds based on latest patch as mentioned here: https://news.blizzard.com/en-us/starcraft2/23893118/starcraft-ii-5-0-11-patch-notes

I am trying to understand how to use the planner with latest patch?

README has an 'UPDATE' section that mentions getting a `data.json` from other repo and importing that to `src/constants/data.json` 
Looks like this file was updated in other repo here: https://github.com/BurnySc2/sc2-techtree/blob/develop/data/data.json
But file in this repo is still 10 months old patch 5.0.9: https://github.com/BurnySc2/sc2-planner/blob/master/src/constants/data.json

Is this going to be updated for the version on https://burnysc2.github.io/sc2-planner/ or I need to download and run it?

Very cool tool, thank you!

**Comment by BurnySc2** [comment]
I was wondering if there is any reason I should support multiple versions for the sc2-planner, so you can specify the patches and it will adjust the cost and build time and requirements of units/structures/upgrades. But then again there is only about one such balance patch per year and why would someone want to make build orders for previous patches. Also what about previously created build orders.

Anyway, thank you for creating the issue and I'll take care updating it soon'ish

**Comment by n7ck** [comment]
Awesome, thanks for fast response, was not expecting that.

Ya I personally just wanted the latest patch always, but not sure about others? - like at least it doesn't totally break if its an old patch build -  so thats better than a lot of other online tools that get updated.

One other thing I was wondering about is units dying (supply being freed up from units dying) any idea how complex that would be to add? So that don't need to build so much supply increasing buildings for longer builds - if there a way to just put in like a (-1 or -2 non-worker death) - or alternatively just like a [ +8_supply 0_mineral ] imaginary building to account for the expected deaths?

Thank you again!
