### ISSUE TITLE
Add about details showing SC2 patch version

### ISSUE THREAD

**Issue by squeakyboots** [BurnySc2/sc2-planner#8]
Thanks for your time on this tool! Would you be open to considering adding the details of the current patch version the tool is built for?

![image](https://user-images.githubusercontent.com/11595454/82066553-d157c700-968c-11ea-8711-a667780ab611.png)

**Comment by BurnySc2** [comment]
Yep, I can add the connected SC2 version to it.

**Comment by BurnySc2** [comment]
Added it in https://github.com/BurnySc2/sc2-planner/commit/806f74a1a4c38beaad6ca98f714d4adc20a25a40
Additionally I have put a link to the patchnotes (liquipedia link).
